

DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name 830c1a156beb4ab28577541b5dd31c90'
 


IF(EXISTS(SELECT 1 FROM 
					[dbo].[InterviewStatus]
				WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM [dbo].[InterviewStatus]
WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 

END