

-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @FirstName NVARCHAR(50) = 'FirstName 94b01f33634e4494a56dca1e9ae65c19'
DECLARE @MiddleName NVARCHAR(50) = 'MiddleName 94b01f33634e4494a56dca1e9ae65c19'
DECLARE @LastName NVARCHAR(50) = 'LastName 94b01f33634e4494a56dca1e9ae65c19'
DECLARE @Email NVARCHAR(50) = 'Email 94b01f33634e4494a56dca1e9ae65c19'
DECLARE @Phone NVARCHAR(50) = 'Phone 94b01f33634e4494a56dca1e9ae65c19'
DECLARE @CVLink NVARCHAR(1000) = 'CVLink 94b01f33634e4494a56dca1e9ae65c19'
DECLARE @CreatedByID BIGINT = 100002
DECLARE @CreatedDate DATETIME = '8/21/2022 10:27:11 AM'
DECLARE @ModifiedByID BIGINT = 33020042
DECLARE @ModifiedDate DATETIME = '11/18/2018 2:02:11 PM'
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updFirstName NVARCHAR(50) = 'FirstName 93d527c0eb04498cac8e3907077beac9'
DECLARE @updMiddleName NVARCHAR(50) = 'MiddleName 93d527c0eb04498cac8e3907077beac9'
DECLARE @updLastName NVARCHAR(50) = 'LastName 93d527c0eb04498cac8e3907077beac9'
DECLARE @updEmail NVARCHAR(50) = 'Email 93d527c0eb04498cac8e3907077beac9'
DECLARE @updPhone NVARCHAR(50) = 'Phone 93d527c0eb04498cac8e3907077beac9'
DECLARE @updCVLink NVARCHAR(1000) = 'CVLink 93d527c0eb04498cac8e3907077beac9'
DECLARE @updCreatedByID BIGINT = 100001
DECLARE @updCreatedDate DATETIME = '3/20/2023 7:51:11 AM'
DECLARE @updModifiedByID BIGINT = 100003
DECLARE @updModifiedDate DATETIME = '12/15/2023 9:12:11 AM'
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[Candidate]
				WHERE 
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updEmail IS NOT NULL THEN (CASE WHEN [Email] = @updEmail THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPhone IS NOT NULL THEN (CASE WHEN [Phone] = @updPhone THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCVLink IS NOT NULL THEN (CASE WHEN [CVLink] = @updCVLink THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[Candidate]
	WHERE 
	(CASE WHEN @FirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @FirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @MiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @MiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @LastName IS NOT NULL THEN (CASE WHEN [LastName] = @LastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Email IS NOT NULL THEN (CASE WHEN [Email] = @Email THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Phone IS NOT NULL THEN (CASE WHEN [Phone] = @Phone THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CVLink IS NOT NULL THEN (CASE WHEN [CVLink] = @CVLink THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[Candidate]
	WHERE 
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updEmail IS NOT NULL THEN (CASE WHEN [Email] = @updEmail THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPhone IS NOT NULL THEN (CASE WHEN [Phone] = @updPhone THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCVLink IS NOT NULL THEN (CASE WHEN [CVLink] = @updCVLink THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'Candidate was not updated', 1
END