

-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @FirstName NVARCHAR(50) = 'FirstName a0f8e48a4d1341ac8f49e9326b34bad8'
DECLARE @MiddleName NVARCHAR(50) = 'MiddleName a0f8e48a4d1341ac8f49e9326b34bad8'
DECLARE @LastName NVARCHAR(50) = 'LastName a0f8e48a4d1341ac8f49e9326b34bad8'
DECLARE @Email NVARCHAR(50) = 'Email a0f8e48a4d1341ac8f49e9326b34bad8'
DECLARE @Phone NVARCHAR(50) = 'Phone a0f8e48a4d1341ac8f49e9326b34bad8'
DECLARE @CVLink NVARCHAR(1000) = 'CVLink a0f8e48a4d1341ac8f49e9326b34bad8'
DECLARE @CreatedByID BIGINT = 100002
DECLARE @CreatedDate DATETIME = '8/13/2020 4:36:32 AM'
DECLARE @ModifiedByID BIGINT = 100003
DECLARE @ModifiedDate DATETIME = '10/29/2022 1:59:32 PM'
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updFirstName NVARCHAR(50) = 'FirstName c0133fc9adce44d695bb73c682b17142'
DECLARE @updMiddleName NVARCHAR(50) = 'MiddleName c0133fc9adce44d695bb73c682b17142'
DECLARE @updLastName NVARCHAR(50) = 'LastName c0133fc9adce44d695bb73c682b17142'
DECLARE @updEmail NVARCHAR(50) = 'Email c0133fc9adce44d695bb73c682b17142'
DECLARE @updPhone NVARCHAR(50) = 'Phone c0133fc9adce44d695bb73c682b17142'
DECLARE @updCVLink NVARCHAR(1000) = 'CVLink c0133fc9adce44d695bb73c682b17142'
DECLARE @updCreatedByID BIGINT = 100004
DECLARE @updCreatedDate DATETIME = '10/8/2021 11:25:32 PM'
DECLARE @updModifiedByID BIGINT = 100003
DECLARE @updModifiedDate DATETIME = '4/6/2022 5:13:32 AM'
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[Candidate]
				WHERE 
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updEmail IS NOT NULL THEN (CASE WHEN [Email] = @updEmail THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPhone IS NOT NULL THEN (CASE WHEN [Phone] = @updPhone THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCVLink IS NOT NULL THEN (CASE WHEN [CVLink] = @updCVLink THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[Candidate]
	WHERE 
	(CASE WHEN @FirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @FirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @MiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @MiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @LastName IS NOT NULL THEN (CASE WHEN [LastName] = @LastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Email IS NOT NULL THEN (CASE WHEN [Email] = @Email THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Phone IS NOT NULL THEN (CASE WHEN [Phone] = @Phone THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CVLink IS NOT NULL THEN (CASE WHEN [CVLink] = @CVLink THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[Candidate]
	WHERE 
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updEmail IS NOT NULL THEN (CASE WHEN [Email] = @updEmail THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPhone IS NOT NULL THEN (CASE WHEN [Phone] = @updPhone THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCVLink IS NOT NULL THEN (CASE WHEN [CVLink] = @updCVLink THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'Candidate was not updated', 1
END