DECLARE @ID BIGINT
DECLARE @Name NVARCHAR(50) = 'Name b32caca28e0e46119081238b311a3543'

IF(NOT EXISTS(SELECT 1 FROM 
					[dbo].[ProposalStatus]
				WHERE 
					(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1))
BEGIN
	INSERT INTO [dbo].[ProposalStatus]
		([Name])
	SELECT 		
		@Name
END

SELECT TOP 1 @ID = [ID] 
FROM 
	[dbo].[ProposalStatus] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1

SELECT @ID