

DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name 73cd2ce7e647449f9d4011be1bc53b92'
 

DELETE FROM [ProposalStatus]
FROM 
	[dbo].[ProposalStatus] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 
