

DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name 23df314cee204d75970a5aa1b0e7c6c1'
 

DELETE FROM [ProposalStatus]
FROM 
	[dbo].[ProposalStatus] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 
