

-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @PositionID BIGINT = 110118
DECLARE @CandidateID BIGINT = 100002
DECLARE @Proposed DATETIME = '2/17/2022 9:59:11 AM'
DECLARE @CurrentStepID BIGINT = 10
DECLARE @StepSetDate DATETIME = '2/17/2022 9:59:11 AM'
DECLARE @NextStepID BIGINT = 9
DECLARE @DueDate DATETIME = '2/17/2022 9:59:11 AM'
DECLARE @StatusID BIGINT = 3
DECLARE @CreatedByID BIGINT = 100003
DECLARE @CreatedDate DATETIME = '7/8/2019 7:46:11 PM'
DECLARE @ModifiedByID BIGINT = 100003
DECLARE @ModifiedDate DATETIME = '7/8/2019 7:46:11 PM'
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updPositionID BIGINT = 100005
DECLARE @updCandidateID BIGINT = 100002
DECLARE @updProposed DATETIME = '5/19/2022 5:33:11 AM'
DECLARE @updCurrentStepID BIGINT = 1
DECLARE @updStepSetDate DATETIME = '10/7/2019 3:19:11 PM'
DECLARE @updNextStepID BIGINT = 5
DECLARE @updDueDate DATETIME = '10/7/2019 3:19:11 PM'
DECLARE @updStatusID BIGINT = 4
DECLARE @updCreatedByID BIGINT = 100002
DECLARE @updCreatedDate DATETIME = '8/16/2022 3:46:11 PM'
DECLARE @updModifiedByID BIGINT = 100002
DECLARE @updModifiedDate DATETIME = '1/5/2020 1:33:11 AM'
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[Proposal]
				WHERE 
	(CASE WHEN @updPositionID IS NOT NULL THEN (CASE WHEN [PositionID] = @updPositionID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCandidateID IS NOT NULL THEN (CASE WHEN [CandidateID] = @updCandidateID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updProposed IS NOT NULL THEN (CASE WHEN [Proposed] = @updProposed THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCurrentStepID IS NOT NULL THEN (CASE WHEN [CurrentStepID] = @updCurrentStepID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updStepSetDate IS NOT NULL THEN (CASE WHEN [StepSetDate] = @updStepSetDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updNextStepID IS NOT NULL THEN (CASE WHEN [NextStepID] = @updNextStepID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updDueDate IS NOT NULL THEN (CASE WHEN [DueDate] = @updDueDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updStatusID IS NOT NULL THEN (CASE WHEN [StatusID] = @updStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[Proposal]
	WHERE 
	(CASE WHEN @PositionID IS NOT NULL THEN (CASE WHEN [PositionID] = @PositionID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CandidateID IS NOT NULL THEN (CASE WHEN [CandidateID] = @CandidateID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Proposed IS NOT NULL THEN (CASE WHEN [Proposed] = @Proposed THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CurrentStepID IS NOT NULL THEN (CASE WHEN [CurrentStepID] = @CurrentStepID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @StepSetDate IS NOT NULL THEN (CASE WHEN [StepSetDate] = @StepSetDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @NextStepID IS NOT NULL THEN (CASE WHEN [NextStepID] = @NextStepID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @DueDate IS NOT NULL THEN (CASE WHEN [DueDate] = @DueDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @StatusID IS NOT NULL THEN (CASE WHEN [StatusID] = @StatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[Proposal]
	WHERE 
	(CASE WHEN @updPositionID IS NOT NULL THEN (CASE WHEN [PositionID] = @updPositionID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCandidateID IS NOT NULL THEN (CASE WHEN [CandidateID] = @updCandidateID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updProposed IS NOT NULL THEN (CASE WHEN [Proposed] = @updProposed THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCurrentStepID IS NOT NULL THEN (CASE WHEN [CurrentStepID] = @updCurrentStepID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updStepSetDate IS NOT NULL THEN (CASE WHEN [StepSetDate] = @updStepSetDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updNextStepID IS NOT NULL THEN (CASE WHEN [NextStepID] = @updNextStepID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updDueDate IS NOT NULL THEN (CASE WHEN [DueDate] = @updDueDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updStatusID IS NOT NULL THEN (CASE WHEN [StatusID] = @updStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'Proposal was not updated', 1
END