

DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name 8287fdb31762473daa8e4b60c4f2831f'
DECLARE @ReqDueDate BIT = True
DECLARE @RequiresRespInDays INT = 190
 

DELETE FROM [ProposalStep]
FROM 
	[dbo].[ProposalStep] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ReqDueDate IS NOT NULL THEN (CASE WHEN [ReqDueDate] = @ReqDueDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @RequiresRespInDays IS NOT NULL THEN (CASE WHEN [RequiresRespInDays] = @RequiresRespInDays THEN 1 ELSE 0 END) ELSE 1 END) = 1 
