

DECLARE @UserID BIGINT = 100002
DECLARE @RoleID BIGINT = 2
 

DELETE FROM [UserRoleSystem]
FROM 
	[dbo].[UserRoleSystem] e
WHERE
	(CASE WHEN @UserID IS NOT NULL THEN (CASE WHEN [UserID] = @UserID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @RoleID IS NOT NULL THEN (CASE WHEN [RoleID] = @RoleID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
