{FIELDS_VARIABLES_LIST_GET}

IF(NOT EXISTS(SELECT 1 FROM 
					[dbo].[{Entity}]
				WHERE 
					{WHERE_FIELDS_LIST}))
BEGIN
	INSERT INTO [dbo].[{Entity}]
		(INSERT_FIELDS_NAMES_LIST)
	SELECT 		
		{INSERT_FIELDS_VALS_LIST}
END

SELECT TOP 1 {PKS_ASSIGNMENT_LIST} 
FROM 
	[dbo].[{Entity}] e
WHERE
	{WHERE_FIELDS_LIST}

SELECT {PKS_VARS_LIST}