

DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name 42b66d799e8a4a1588c63579625bd0a7'
 


IF(EXISTS(SELECT 1 FROM 
					[dbo].[ProposalStatus]
				WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM [dbo].[ProposalStatus]
WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 

END