

DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name 0fb8b7da0cee45568dbaaf9c4bb7d211'
DECLARE @Value NVARCHAR(1000) = 'Value 0fb8b7da0cee45568dbaaf9c4bb7d211'
DECLARE @CandidateID BIGINT = 100001
 

DELETE FROM [CandidateProperty]
FROM 
	[dbo].[CandidateProperty] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Value IS NOT NULL THEN (CASE WHEN [Value] = @Value THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CandidateID IS NOT NULL THEN (CASE WHEN [CandidateID] = @CandidateID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
