

DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name 933d5e37a44d4c12a7603f2056ae19c5'
DECLARE @UUID NVARCHAR(50) = 'UUID 933d5e37a44d4c12a7603f2056ae19c5'
DECLARE @ParentID BIGINT = NULL
DECLARE @ManagerID BIGINT = 100003
 


IF(NOT EXISTS(SELECT 1 FROM 
					[dbo].[Department]
				WHERE 
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @UUID IS NOT NULL THEN (CASE WHEN [UUID] = @UUID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ParentID IS NOT NULL THEN (CASE WHEN [ParentID] = @ParentID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ManagerID IS NOT NULL THEN (CASE WHEN [ManagerID] = @ManagerID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN
	INSERT INTO [dbo].[Department]
		(
	 [Name],
	 [UUID],
	 [ParentID],
	 [ManagerID]
		)
	SELECT 		
			 @Name,
	 @UUID,
	 @ParentID,
	 @ManagerID
END

SELECT TOP 1 
	@ID = [ID]
FROM 
	[dbo].[Department] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @UUID IS NOT NULL THEN (CASE WHEN [UUID] = @UUID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ParentID IS NOT NULL THEN (CASE WHEN [ParentID] = @ParentID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ManagerID IS NOT NULL THEN (CASE WHEN [ManagerID] = @ManagerID THEN 1 ELSE 0 END) ELSE 1 END) = 1 

SELECT 
	@ID
