

DECLARE @ProposalID BIGINT = 100004
DECLARE @CommentID BIGINT = 100001
 

DELETE FROM [ProposalComment]
FROM 
	[dbo].[ProposalComment] e
WHERE
	(CASE WHEN @ProposalID IS NOT NULL THEN (CASE WHEN [ProposalID] = @ProposalID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CommentID IS NOT NULL THEN (CASE WHEN [CommentID] = @CommentID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
