

DECLARE @CandidateID BIGINT = 110118
DECLARE @UserID BIGINT = 100001
DECLARE @RoleID BIGINT = 3
 

DELETE FROM [UserRoleCandidate]
FROM 
	[dbo].[UserRoleCandidate] e
WHERE
	(CASE WHEN @CandidateID IS NOT NULL THEN (CASE WHEN [CandidateID] = @CandidateID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @UserID IS NOT NULL THEN (CASE WHEN [UserID] = @UserID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @RoleID IS NOT NULL THEN (CASE WHEN [RoleID] = @RoleID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
