DECLARE @ID BIGINT
DECLARE @Text NVARCHAR(4000) = 'Text 556f8522b133407ba6b9879908b8adda'
DECLARE @CreatedDate DATETIME = '4/18/2021 10:33:03 PM'
DECLARE @CreatedByID BIGINT = 33020024
DECLARE @ModifiedDate DATETIME = '2/26/2020 4:22:03 PM'
DECLARE @ModifiedByID BIGINT = 100003

DELETE FROM [dbo].[Comment]
WHERE
	(CASE WHEN @Text IS NOT NULL THEN (CASE WHEN [Text] = @Text THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND 
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND 
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND 
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND 
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1