

DECLARE @UserID BIGINT = 33020042
DECLARE @RoleID BIGINT = 4
 


IF(NOT EXISTS(SELECT 1 FROM 
					[dbo].[UserRoleSystem]
				WHERE 
	(CASE WHEN @UserID IS NOT NULL THEN (CASE WHEN [UserID] = @UserID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @RoleID IS NOT NULL THEN (CASE WHEN [RoleID] = @RoleID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN
	INSERT INTO [dbo].[UserRoleSystem]
		(
	 [UserID],
	 [RoleID]
		)
	SELECT 		
			 @UserID,
	 @RoleID
END

SELECT TOP 1 @ID = [ID] 
FROM 
	[dbo].[UserRoleSystem] e
WHERE
	(CASE WHEN @UserID IS NOT NULL THEN (CASE WHEN [UserID] = @UserID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @RoleID IS NOT NULL THEN (CASE WHEN [RoleID] = @RoleID THEN 1 ELSE 0 END) ELSE 1 END) = 1 

SELECT @ID