

DECLARE @ID BIGINT = NULL
DECLARE @Name NVARCHAR(50) = 'Name 9313cdf4ea9d431aa180b75afe2df762'
 

DELETE FROM [PositionStatus]
FROM 
	[dbo].[PositionStatus] e
WHERE
	(CASE WHEN @Name IS NOT NULL THEN (CASE WHEN [Name] = @Name THEN 1 ELSE 0 END) ELSE 1 END) = 1 
