{FIELDS_VARIABLES_LIST_UPDATED}
DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
					[dbo].[{Entity}]
				WHERE 
					{WHERE_FIELDS_LIST}))
BEGIN
	SET @Fail = 1
END

DELETE FROM [dbo].[{Entity}]
WHERE
	{WHERE_FIELDS_LIST}

IF(@Fail = 1) 
BEGIN
	THROW 51001, '{Entity} was not updated', 1
END